version: "2"

linters:
  enable:
    - errcheck
    - staticcheck
    - ineffassign
    - govet
    - gosec
    - unused

  settings:
    errcheck:
      exclude-functions:
        - (net/http.ResponseWriter).Write
        - (io.Writer).Write
        - (io.Closer).Close
        - fmt.Fprintf
        - fmt.Fprintln
        - (*encoding/json.Encoder).Encode
        - (*encoding/json.Decoder).Decode
    gosec:
      excludes:
        - G304
        - G101
        - G404
        - G104
        - G306

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
          - staticcheck
    paths:
      - vendor
