//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ReadinessResponseStatus.
const (
	NotReady ReadinessResponseStatus = "not_ready"
	Ready    ReadinessResponseStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadinessResponseStatus enum.
func (e ReadinessResponseStatus) Valid() bool {
	switch e {
	case NotReady:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for WalletStatusBalanceStatus.
const (
	Depleted WalletStatusBalanceStatus = "depleted"
	Ok       WalletStatusBalanceStatus = "ok"
)

// Valid indicates whether the value is a known member of the WalletStatusBalanceStatus enum.
func (e WalletStatusBalanceStatus) Valid() bool {
	switch e {
	case Depleted:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ListQuotasParamsStatus.
const (
	False ListQuotasParamsStatus = "false"
	True  ListQuotasParamsStatus = "true"
)

// Valid indicates whether the value is a known member of the ListQuotasParamsStatus enum.
func (e ListQuotasParamsStatus) Valid() bool {
	switch e {
	case False:
		return true
	case True:
		return true
	default:
		return false
	}
}

// Defines values for ListRatesParamsFormat.
const (
	ListRatesParamsFormatCsv ListRatesParamsFormat = "csv"
)

// Valid indicates whether the value is a known member of the ListRatesParamsFormat enum.
func (e ListRatesParamsFormat) Valid() bool {
	switch e {
	case ListRatesParamsFormatCsv:
		return true
	default:
		return false
	}
}

// Defines values for GetCostBreakdownParamsFormat.
const (
	GetCostBreakdownParamsFormatCsv GetCostBreakdownParamsFormat = "csv"
)

// Valid indicates whether the value is a known member of the GetCostBreakdownParamsFormat enum.
func (e GetCostBreakdownParamsFormat) Valid() bool {
	switch e {
	case GetCostBreakdownParamsFormatCsv:
		return true
	default:
		return false
	}
}

// Defines values for GetCostReportParamsGroupBy.
const (
	Meter        GetCostReportParamsGroupBy = "meter"
	Project      GetCostReportParamsGroupBy = "project"
	ResourceType GetCostReportParamsGroupBy = "resource_type"
	Tenant       GetCostReportParamsGroupBy = "tenant"
	User         GetCostReportParamsGroupBy = "user"
)

// Valid indicates whether the value is a known member of the GetCostReportParamsGroupBy enum.
func (e GetCostReportParamsGroupBy) Valid() bool {
	switch e {
	case Meter:
		return true
	case Project:
		return true
	case ResourceType:
		return true
	case Tenant:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for GetCostReportParamsResolution.
const (
	Daily GetCostReportParamsResolution = "daily"
)

// Valid indicates whether the value is a known member of the GetCostReportParamsResolution enum.
func (e GetCostReportParamsResolution) Valid() bool {
	switch e {
	case Daily:
		return true
	default:
		return false
	}
}

// Defines values for GetCostReportParamsFormat.
const (
	GetCostReportParamsFormatCsv GetCostReportParamsFormat = "csv"
)

// Valid indicates whether the value is a known member of the GetCostReportParamsFormat enum.
func (e GetCostReportParamsFormat) Valid() bool {
	switch e {
	case GetCostReportParamsFormatCsv:
		return true
	default:
		return false
	}
}

// AlertRecord defines model for AlertRecord.
type AlertRecord struct {
	Consumed     *float64   `json:"consumed,omitempty"`
	FiredAt      *time.Time `json:"fired_at,omitempty"`
	Id           *int64     `json:"id,omitempty"`
	LimitValue   *float64   `json:"limit_value,omitempty"`
	MeterName    *string    `json:"meter_name,omitempty"`
	Period       *string    `json:"period,omitempty"`
	State        *string    `json:"state,omitempty"`
	TenantId     *string    `json:"tenant_id,omitempty"`
	ThresholdPct *float64   `json:"threshold_pct,omitempty"`
}

// CloudEvent CloudEvents 1.0 structured-mode JSON envelope
type CloudEvent struct {
	// Data Event payload; shape depends on type. See ComputeInstanceEventData, ClusterEventData, MaaSEventData.
	Data *CloudEvent_Data `json:"data,omitempty"`

	// Datacontenttype Example: application/json
	Datacontenttype *string `json:"datacontenttype,omitempty"`

	// Id Example: evt-abc123
	Id string `json:"id"`

	// Source Example: /osac/metering-collector
	Source string `json:"source"`

	// Specversion Example: 1.0
	Specversion string     `json:"specversion"`
	Subject     *string    `json:"subject,omitempty"`
	Time        *time.Time `json:"time,omitempty"`

	// Type Event type. Known types: osac.compute_instance.lifecycle, osac.cluster.lifecycle, osac.model.lifecycle, inference.tokens.used
	//
	// Example: inference.tokens.used
	Type string `json:"type"`
}

// CloudEvent_Data Event payload; shape depends on type. See ComputeInstanceEventData, ClusterEventData, MaaSEventData.
type CloudEvent_Data struct {
	union json.RawMessage
}

// ClusterEventData OSAC metering collector CaaS schema
type ClusterEventData struct {
	ClusterId         *string  `json:"cluster_id,omitempty"`
	DurationSeconds   *float64 `json:"duration_seconds,omitempty"`
	HostType          *string  `json:"host_type,omitempty"`
	NodeCount         *int32   `json:"node_count,omitempty"`
	State             *string  `json:"state,omitempty"`
	Template          *string  `json:"template,omitempty"`
	TenantId          *string  `json:"tenant_id,omitempty"`
	WorkerNodeSeconds *int64   `json:"worker_node_seconds,omitempty"`
}

// ComputeInstanceEventData OSAC metering collector VMaaS schema
type ComputeInstanceEventData struct {
	CatalogItem      *string  `json:"catalog_item,omitempty"`
	Cores            *int32   `json:"cores,omitempty"`
	CpuCoreSeconds   *int64   `json:"cpu_core_seconds,omitempty"`
	DurationSeconds  *float64 `json:"duration_seconds,omitempty"`
	InstanceId       *string  `json:"instance_id,omitempty"`
	MemoryGib        *int32   `json:"memory_gib,omitempty"`
	MemoryGibSeconds *int64   `json:"memory_gib_seconds,omitempty"`
	State            *string  `json:"state,omitempty"`
	Template         *string  `json:"template,omitempty"`
	TenantId         *string  `json:"tenant_id,omitempty"`
}

// CostBreakdownMeta defines model for CostBreakdownMeta.
type CostBreakdownMeta struct {
	Count   *int               `json:"count,omitempty"`
	Filters *map[string]string `json:"filters,omitempty"`
}

// CostBreakdownResponse defines model for CostBreakdownResponse.
type CostBreakdownResponse struct {
	Data *[]CostBreakdownRow `json:"data,omitempty"`
	Meta *CostBreakdownMeta  `json:"meta,omitempty"`
}

// CostBreakdownRow defines model for CostBreakdownRow.
type CostBreakdownRow struct {
	CostAmount   *float64 `json:"cost_amount,omitempty"`
	CostType     *string  `json:"cost_type,omitempty"`
	Currency     *string  `json:"currency,omitempty"`
	Date         *string  `json:"date,omitempty"`
	MeterName    *string  `json:"meter_name,omitempty"`
	MeteredValue *float64 `json:"metered_value,omitempty"`
	ProjectId    *string  `json:"project_id,omitempty"`
	ResourceId   *string  `json:"resource_id,omitempty"`
	ResourceType *string  `json:"resource_type,omitempty"`
	TenantId     *string  `json:"tenant_id,omitempty"`
	UserId       *string  `json:"user_id,omitempty"`
}

// CostReportMeta defines model for CostReportMeta.
type CostReportMeta struct {
	Filters    *map[string]string `json:"filters,omitempty"`
	GroupBy    *string            `json:"group_by,omitempty"`
	Period     *string            `json:"period,omitempty"`
	Resolution *string            `json:"resolution,omitempty"`
	Total      *KokuCostTotal     `json:"total,omitempty"`
}

// CostReportResponse defines model for CostReportResponse.
type CostReportResponse struct {
	Data *[]CostReportRow `json:"data,omitempty"`
	Meta *CostReportMeta  `json:"meta,omitempty"`
}

// CostReportRow defines model for CostReportRow.
type CostReportRow struct {
	Cost     *float64 `json:"cost,omitempty"`
	Currency *string  `json:"currency,omitempty"`

	// Date Present only when resolution=daily
	Date               *string  `json:"date,omitempty"`
	Entries            *int     `json:"entries,omitempty"`
	Group              *string  `json:"group,omitempty"`
	InfrastructureCost *float64 `json:"infrastructure_cost,omitempty"`
	SupplementaryCost  *float64 `json:"supplementary_cost,omitempty"`
}

// CreateWalletRequest defines model for CreateWalletRequest.
type CreateWalletRequest struct {
	Currency   *string    `json:"currency,omitempty"`
	ProjectId  *string    `json:"project_id,omitempty"`
	TenantId   string     `json:"tenant_id"`
	Thresholds *[]float64 `json:"thresholds,omitempty"`
}

// DiagnosticInfo defines model for DiagnosticInfo.
type DiagnosticInfo struct {
	AuthIssuerUrl           *string `json:"auth_issuer_url,omitempty"`
	CustomMetricsConfigPath *string `json:"custom_metrics_config_path,omitempty"`
	DebugDashboard          *bool   `json:"debug_dashboard,omitempty"`
	IngestListenAddr        *string `json:"ingest_listen_addr,omitempty"`

	// InventoryDbHost Database URL with credentials masked
	InventoryDbHost   *string `json:"inventory_db_host,omitempty"`
	LogFormat         *string `json:"log_format,omitempty"`
	LogLevel          *string `json:"log_level,omitempty"`
	MeteringInterval  *string `json:"metering_interval,omitempty"`
	MetricsPort       *string `json:"metrics_port,omitempty"`
	OsacBaseUrl       *string `json:"osac_base_url,omitempty"`
	OsacCaCertSet     *bool   `json:"osac_ca_cert_set,omitempty"`
	OsacTokenSet      *bool   `json:"osac_token_set,omitempty"`
	RatingInterval    *string `json:"rating_interval,omitempty"`
	ReconcileInterval *string `json:"reconcile_interval,omitempty"`
	SplunkHecUrl      *string `json:"splunk_hec_url,omitempty"`
	SplunkIndex       *string `json:"splunk_index,omitempty"`
	SplunkTokenSet    *bool   `json:"splunk_token_set,omitempty"`
}

// EntitlementValue IPP-compatible entitlement value. Matches the entitlementValue struct from the IPP external-metering plugin client.
type EntitlementValue struct {
	Balance   *float64 `json:"balance,omitempty"`
	HasAccess *bool    `json:"hasAccess,omitempty"`
	Overage   *float64 `json:"overage,omitempty"`
	Usage     *float64 `json:"usage,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// KokuCostBlock defines model for KokuCostBlock.
type KokuCostBlock struct {
	Markup *KokuCostLayer `json:"markup,omitempty"`
	Raw    *KokuCostLayer `json:"raw,omitempty"`
	Total  *KokuCostLayer `json:"total,omitempty"`
	Usage  *KokuCostLayer `json:"usage,omitempty"`
}

// KokuCostLayer defines model for KokuCostLayer.
type KokuCostLayer struct {
	Units *string  `json:"units,omitempty"`
	Value *float64 `json:"value,omitempty"`
}

// KokuCostTotal defines model for KokuCostTotal.
type KokuCostTotal struct {
	Cost           *KokuCostBlock `json:"cost,omitempty"`
	CostUnits      *string        `json:"cost_units,omitempty"`
	Infrastructure *KokuCostBlock `json:"infrastructure,omitempty"`
	Supplementary  *KokuCostBlock `json:"supplementary,omitempty"`
}

// MaaSEventData MaaS / IPP external-metering event data. Accepts both legacy mock format and the real IPP external-metering plugin format.
type MaaSEventData struct {
	// CacheCreationTokens Subset of prompt_tokens
	CacheCreationTokens *int64 `json:"cache_creation_tokens,omitempty"`

	// CachedInputTokens Subset of prompt_tokens; parsed for observability, not billed separately
	CachedInputTokens *int64   `json:"cached_input_tokens,omitempty"`
	CompletionTokens  *int64   `json:"completion_tokens,omitempty"`
	CostCenter        *string  `json:"cost_center,omitempty"`
	DurationMs        *int64   `json:"duration_ms,omitempty"`
	DurationSeconds   *float64 `json:"duration_seconds,omitempty"`
	Group             *string  `json:"group,omitempty"`
	Model             *string  `json:"model,omitempty"`
	ModelId           *string  `json:"model_id,omitempty"`
	ModelName         *string  `json:"model_name,omitempty"`
	OrganizationId    *string  `json:"organization_id,omitempty"`
	PromptTokens      *int64   `json:"prompt_tokens,omitempty"`
	Provider          *string  `json:"provider,omitempty"`

	// ReasoningTokens Subset of completion_tokens (o1/o3/DeepSeek R1)
	ReasoningTokens *int64  `json:"reasoning_tokens,omitempty"`
	RequestCount    *int64  `json:"request_count,omitempty"`
	Requests        *int64  `json:"requests,omitempty"`
	State           *string `json:"state,omitempty"`
	Subscription    *string `json:"subscription,omitempty"`
	Template        *string `json:"template,omitempty"`
	TenantId        *string `json:"tenant_id,omitempty"`
	TokensIn        *int64  `json:"tokens_in,omitempty"`
	TokensOut       *int64  `json:"tokens_out,omitempty"`
	TotalTokens     *int64  `json:"total_tokens,omitempty"`
	User            *string `json:"user,omitempty"`
}

// PipelineSummary defines model for PipelineSummary.
type PipelineSummary struct {
	CostEntries     *int `json:"cost_entries,omitempty"`
	LiveClusters    *int `json:"live_clusters,omitempty"`
	LiveModels      *int `json:"live_models,omitempty"`
	LiveVms         *int `json:"live_vms,omitempty"`
	MeteringEntries *int `json:"metering_entries,omitempty"`
	Rates           *int `json:"rates,omitempty"`
	RawEvents       *int `json:"raw_events,omitempty"`
}

// QuotaRecord defines model for QuotaRecord.
type QuotaRecord struct {
	EffectiveFrom *time.Time `json:"effective_from,omitempty"`
	EffectiveTo   *time.Time `json:"effective_to,omitempty"`
	Id            *int64     `json:"id,omitempty"`
	LimitValue    *float64   `json:"limit_value,omitempty"`
	MeterName     *string    `json:"meter_name,omitempty"`
	Name          *string    `json:"name,omitempty"`

	// Period Billing period: monthly, weekly, daily, or custom. Defaults to "monthly" if omitted.
	Period *string `json:"period,omitempty"`

	// Policy Enforcement policy. Defaults to "deny".
	Policy       *string `json:"policy,omitempty"`
	ProjectId    *string `json:"project_id,omitempty"`
	ResourceType *string `json:"resource_type,omitempty"`
	TenantId     *string `json:"tenant_id,omitempty"`

	// Thresholds Alert threshold percentages
	Thresholds *[]float64 `json:"thresholds,omitempty"`

	// Unit Unit of the quota. Currency codes (USD, EUR, etc.) indicate a budget quota; otherwise a metering unit.
	Unit *string `json:"unit,omitempty"`
}

// QuotaStatus defines model for QuotaStatus.
type QuotaStatus struct {
	Alerts     *[]AlertRecord `json:"alerts,omitempty"`
	Consumed   *float64       `json:"consumed,omitempty"`
	Limit      *float64       `json:"limit,omitempty"`
	MeterName  *string        `json:"meter_name,omitempty"`
	Percentage *float64       `json:"percentage,omitempty"`

	// Thresholds Threshold percentage keys mapped to breached (true/false)
	Thresholds *map[string]bool `json:"thresholds,omitempty"`
	Unit       *string          `json:"unit,omitempty"`
}

// QuotaStatusResponse defines model for QuotaStatusResponse.
type QuotaStatusResponse struct {
	Period *string `json:"period,omitempty"`

	// Projects Per-project quota statuses (present only when project-scoped quotas exist)
	Projects *map[string][]QuotaStatus `json:"projects,omitempty"`
	Quotas   *[]QuotaStatus            `json:"quotas,omitempty"`
	TenantId *string                   `json:"tenant_id,omitempty"`
}

// QuotaWithStatus QuotaRecord enriched with live consumption data
type QuotaWithStatus struct {
	Consumed      *float64   `json:"consumed,omitempty"`
	EffectiveFrom *time.Time `json:"effective_from,omitempty"`
	EffectiveTo   *time.Time `json:"effective_to,omitempty"`
	Id            *int64     `json:"id,omitempty"`
	LimitValue    *float64   `json:"limit_value,omitempty"`
	MeterName     *string    `json:"meter_name,omitempty"`
	Name          *string    `json:"name,omitempty"`
	Percentage    *float64   `json:"percentage,omitempty"`

	// Period Billing period: monthly, weekly, daily, or custom. Defaults to "monthly" if omitted.
	Period *string `json:"period,omitempty"`

	// Policy Enforcement policy. Defaults to "deny".
	Policy       *string          `json:"policy,omitempty"`
	ProjectId    *string          `json:"project_id,omitempty"`
	ResourceType *string          `json:"resource_type,omitempty"`
	TenantId     *string          `json:"tenant_id,omitempty"`
	Thresholds   *map[string]bool `json:"thresholds,omitempty"`

	// Unit Unit of the quota. Currency codes (USD, EUR, etc.) indicate a budget quota; otherwise a metering unit.
	Unit *string `json:"unit,omitempty"`
}

// RateRecord defines model for RateRecord.
type RateRecord struct {
	// CostType Infrastructure or Supplementary
	CostType      *string    `json:"cost_type,omitempty"`
	Currency      *string    `json:"currency,omitempty"`
	Description   *string    `json:"description,omitempty"`
	EffectiveFrom *time.Time `json:"effective_from,omitempty"`
	EffectiveTo   *time.Time `json:"effective_to,omitempty"`
	Id            *int64     `json:"id,omitempty"`
	InstanceType  *string    `json:"instance_type,omitempty"`
	KokuMetric    *string    `json:"koku_metric,omitempty"`
	MeterName     *string    `json:"meter_name,omitempty"`
	PricePerUnit  *string    `json:"price_per_unit,omitempty"`
	ResourceType  *string    `json:"resource_type,omitempty"`
	TenantId      *string    `json:"tenant_id,omitempty"`
	TierMode      *string    `json:"tier_mode,omitempty"`
	TierPeriod    *string    `json:"tier_period,omitempty"`
	Tiers         *[]Tier    `json:"tiers,omitempty"`
}

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	// Error Present only when not ready
	Error  *string                  `json:"error,omitempty"`
	Status *ReadinessResponseStatus `json:"status,omitempty"`
}

// ReadinessResponseStatus defines model for ReadinessResponse.Status.
type ReadinessResponseStatus string

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	// Status Example: ok
	Status *string `json:"status,omitempty"`
}

// Tier defines model for Tier.
type Tier struct {
	PricePerUnit string `json:"price_per_unit"`

	// UpTo Upper bound of tier; null means unlimited
	UpTo *float64 `json:"up_to,omitempty"`
}

// WalletActionRequest defines model for WalletActionRequest.
type WalletActionRequest struct {
	Amount      *string `json:"amount,omitempty"`
	Currency    *string `json:"currency,omitempty"`
	ExternalRef *string `json:"external_ref,omitempty"`
	Reason      *string `json:"reason,omitempty"`
}

// WalletLedgerEntry defines model for WalletLedgerEntry.
type WalletLedgerEntry struct {
	Amount       *string    `json:"amount,omitempty"`
	BalanceAfter *string    `json:"balance_after,omitempty"`
	CostEntryId  *int64     `json:"cost_entry_id,omitempty"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`
	Currency     *string    `json:"currency,omitempty"`
	EntryType    *string    `json:"entry_type,omitempty"`
	ExternalRef  *string    `json:"external_ref,omitempty"`
	Id           *int64     `json:"id,omitempty"`
	Reason       *string    `json:"reason,omitempty"`
	WalletId     *string    `json:"wallet_id,omitempty"`
}

// WalletRecord defines model for WalletRecord.
type WalletRecord struct {
	Balance          *string             `json:"balance,omitempty"`
	BalanceFloor     *string             `json:"balance_floor,omitempty"`
	CreatedAt        *time.Time          `json:"created_at,omitempty"`
	Currency         *string             `json:"currency,omitempty"`
	Id               *openapi_types.UUID `json:"id,omitempty"`
	LifecycleState   *string             `json:"lifecycle_state,omitempty"`
	ProjectId        *string             `json:"project_id,omitempty"`
	ReferenceBalance *string             `json:"reference_balance,omitempty"`
	TenantId         *string             `json:"tenant_id,omitempty"`
	Thresholds       *[]float64          `json:"thresholds,omitempty"`
	UpdatedAt        *time.Time          `json:"updated_at,omitempty"`
}

// WalletStatus defines model for WalletStatus.
type WalletStatus struct {
	Balance          *string                    `json:"balance,omitempty"`
	BalanceFloor     *string                    `json:"balance_floor,omitempty"`
	BalanceStatus    *WalletStatusBalanceStatus `json:"balance_status,omitempty"`
	Currency         *string                    `json:"currency,omitempty"`
	ReferenceBalance *string                    `json:"reference_balance,omitempty"`
	RemainingPct     *float64                   `json:"remaining_pct,omitempty"`
	TenantId         *string                    `json:"tenant_id,omitempty"`
	Thresholds       *map[string]bool           `json:"thresholds,omitempty"`
	WalletId         *string                    `json:"wallet_id,omitempty"`
	WithinBalance    *bool                      `json:"within_balance,omitempty"`
}

// WalletStatusBalanceStatus defines model for WalletStatus.BalanceStatus.
type WalletStatusBalanceStatus string

// GetEntitlementValueParams defines parameters for GetEntitlementValue.
type GetEntitlementValueParams struct {
	// Model Model name (informational, not yet used for filtering)
	Model *string `form:"model,omitempty" json:"model,omitempty"`
}

// ListQuotasParams defines parameters for ListQuotas.
type ListQuotasParams struct {
	// TenantId Filter by tenant ID
	TenantId *string `form:"tenant_id,omitempty" json:"tenant_id,omitempty"`

	// Status When "true", enriches each quota with consumed/percentage/thresholds
	Status *ListQuotasParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListQuotasParamsStatus defines parameters for ListQuotas.
type ListQuotasParamsStatus string

// ListQuotas200JSONResponseBody_Quotas_Item defines parameters for ListQuotas.
type ListQuotas200JSONResponseBody_Quotas_Item struct {
	union json.RawMessage
}

// ListRatesParams defines parameters for ListRates.
type ListRatesParams struct {
	// TenantId Filter rates by tenant ID
	TenantId *string `form:"tenant_id,omitempty" json:"tenant_id,omitempty"`

	// Format Set to "csv" for CSV export
	Format *ListRatesParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// ListRatesParamsFormat defines parameters for ListRates.
type ListRatesParamsFormat string

// GetCostBreakdownParams defines parameters for GetCostBreakdown.
type GetCostBreakdownParams struct {
	// TenantId Filter by tenant ID
	TenantId *string `form:"tenant_id,omitempty" json:"tenant_id,omitempty"`

	// ResourceType Filter by resource type
	ResourceType *string `form:"resource_type,omitempty" json:"resource_type,omitempty"`

	// From Start date (YYYY-MM-DD or RFC3339); defaults to first of current month
	From *string `form:"from,omitempty" json:"from,omitempty"`

	// To End date (YYYY-MM-DD or RFC3339); defaults to now
	To *string `form:"to,omitempty" json:"to,omitempty"`

	// Limit Maximum rows to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Format Set to "csv" for CSV export
	Format *GetCostBreakdownParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// GetCostBreakdownParamsFormat defines parameters for GetCostBreakdown.
type GetCostBreakdownParamsFormat string

// GetCostReportParams defines parameters for GetCostReport.
type GetCostReportParams struct {
	// TenantId Filter by tenant ID
	TenantId *string `form:"tenant_id,omitempty" json:"tenant_id,omitempty"`

	// ResourceType Filter by resource type
	ResourceType *string `form:"resource_type,omitempty" json:"resource_type,omitempty"`

	// GroupBy Grouping dimension
	GroupBy *GetCostReportParamsGroupBy `form:"group_by,omitempty" json:"group_by,omitempty"`

	// Resolution Set to "daily" for per-day rows
	Resolution *GetCostReportParamsResolution `form:"resolution,omitempty" json:"resolution,omitempty"`

	// Period Month in YYYY-MM format (default current month)
	Period *string `form:"period,omitempty" json:"period,omitempty"`

	// From Start date (YYYY-MM-DD or RFC3339); overrides period
	From *string `form:"from,omitempty" json:"from,omitempty"`

	// To End date (YYYY-MM-DD or RFC3339); defaults to now
	To *string `form:"to,omitempty" json:"to,omitempty"`

	// Format Set to "csv" for CSV export
	Format *GetCostReportParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// GetCostReportParamsGroupBy defines parameters for GetCostReport.
type GetCostReportParamsGroupBy string

// GetCostReportParamsResolution defines parameters for GetCostReport.
type GetCostReportParamsResolution string

// GetCostReportParamsFormat defines parameters for GetCostReport.
type GetCostReportParamsFormat string

// GetWalletLedgerParams defines parameters for GetWalletLedger.
type GetWalletLedgerParams struct {
	// Limit Maximum number of entries to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// IngestEventJSONRequestBody defines body for IngestEvent for application/json ContentType.
type IngestEventJSONRequestBody = CloudEvent

// CreateQuotaJSONRequestBody defines body for CreateQuota for application/json ContentType.
type CreateQuotaJSONRequestBody = QuotaRecord

// UpdateQuotaJSONRequestBody defines body for UpdateQuota for application/json ContentType.
type UpdateQuotaJSONRequestBody = QuotaRecord

// CreateWalletJSONRequestBody defines body for CreateWallet for application/json ContentType.
type CreateWalletJSONRequestBody = CreateWalletRequest

// AdjustWalletJSONRequestBody defines body for AdjustWallet for application/json ContentType.
type AdjustWalletJSONRequestBody = WalletActionRequest

// TopUpWalletJSONRequestBody defines body for TopUpWallet for application/json ContentType.
type TopUpWalletJSONRequestBody = WalletActionRequest

// AsComputeInstanceEventData returns the union data inside the CloudEvent_Data as a ComputeInstanceEventData
func (t CloudEvent_Data) AsComputeInstanceEventData() (ComputeInstanceEventData, error) {
	var body ComputeInstanceEventData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComputeInstanceEventData overwrites any union data inside the CloudEvent_Data as the provided ComputeInstanceEventData
func (t *CloudEvent_Data) FromComputeInstanceEventData(v ComputeInstanceEventData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComputeInstanceEventData performs a merge with any union data inside the CloudEvent_Data, using the provided ComputeInstanceEventData
func (t *CloudEvent_Data) MergeComputeInstanceEventData(v ComputeInstanceEventData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsClusterEventData returns the union data inside the CloudEvent_Data as a ClusterEventData
func (t CloudEvent_Data) AsClusterEventData() (ClusterEventData, error) {
	var body ClusterEventData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromClusterEventData overwrites any union data inside the CloudEvent_Data as the provided ClusterEventData
func (t *CloudEvent_Data) FromClusterEventData(v ClusterEventData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeClusterEventData performs a merge with any union data inside the CloudEvent_Data, using the provided ClusterEventData
func (t *CloudEvent_Data) MergeClusterEventData(v ClusterEventData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMaaSEventData returns the union data inside the CloudEvent_Data as a MaaSEventData
func (t CloudEvent_Data) AsMaaSEventData() (MaaSEventData, error) {
	var body MaaSEventData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMaaSEventData overwrites any union data inside the CloudEvent_Data as the provided MaaSEventData
func (t *CloudEvent_Data) FromMaaSEventData(v MaaSEventData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMaaSEventData performs a merge with any union data inside the CloudEvent_Data, using the provided MaaSEventData
func (t *CloudEvent_Data) MergeMaaSEventData(v MaaSEventData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CloudEvent_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CloudEvent_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsQuotaRecord returns the union data inside the ListQuotas200JSONResponseBody_Quotas_Item as a QuotaRecord
func (t ListQuotas200JSONResponseBody_Quotas_Item) AsQuotaRecord() (QuotaRecord, error) {
	var body QuotaRecord
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuotaRecord overwrites any union data inside the ListQuotas200JSONResponseBody_Quotas_Item as the provided QuotaRecord
func (t *ListQuotas200JSONResponseBody_Quotas_Item) FromQuotaRecord(v QuotaRecord) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuotaRecord performs a merge with any union data inside the ListQuotas200JSONResponseBody_Quotas_Item, using the provided QuotaRecord
func (t *ListQuotas200JSONResponseBody_Quotas_Item) MergeQuotaRecord(v QuotaRecord) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuotaWithStatus returns the union data inside the ListQuotas200JSONResponseBody_Quotas_Item as a QuotaWithStatus
func (t ListQuotas200JSONResponseBody_Quotas_Item) AsQuotaWithStatus() (QuotaWithStatus, error) {
	var body QuotaWithStatus
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuotaWithStatus overwrites any union data inside the ListQuotas200JSONResponseBody_Quotas_Item as the provided QuotaWithStatus
func (t *ListQuotas200JSONResponseBody_Quotas_Item) FromQuotaWithStatus(v QuotaWithStatus) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuotaWithStatus performs a merge with any union data inside the ListQuotas200JSONResponseBody_Quotas_Item, using the provided QuotaWithStatus
func (t *ListQuotas200JSONResponseBody_Quotas_Item) MergeQuotaWithStatus(v QuotaWithStatus) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ListQuotas200JSONResponseBody_Quotas_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ListQuotas200JSONResponseBody_Quotas_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetEntitlementValue IPP-compatible balance / entitlement check
	// (GET /api/v1/customers/{customerID}/entitlements/{featureKey}/value)
	GetEntitlementValue(w http.ResponseWriter, r *http.Request, customerID string, featureKey string, params GetEntitlementValueParams)
	// GetDebugConfig Return runtime configuration (sanitized)
	// (GET /api/v1/debug/config)
	GetDebugConfig(w http.ResponseWriter, r *http.Request)
	// IngestEvent Ingest a CloudEvents 1.0 envelope
	// (POST /api/v1/events)
	IngestEvent(w http.ResponseWriter, r *http.Request)
	// ListQuotas List all quotas
	// (GET /api/v1/quotas)
	ListQuotas(w http.ResponseWriter, r *http.Request, params ListQuotasParams)
	// CreateQuota Create a quota or budget
	// (POST /api/v1/quotas)
	CreateQuota(w http.ResponseWriter, r *http.Request)
	// DeleteQuota Soft-delete a quota
	// (DELETE /api/v1/quotas/{id})
	DeleteQuota(w http.ResponseWriter, r *http.Request, id int64)
	// UpdateQuota Update an existing quota
	// (PUT /api/v1/quotas/{id})
	UpdateQuota(w http.ResponseWriter, r *http.Request, id int64)
	// GetQuotaStatus Get quota status for a tenant
	// (GET /api/v1/quotas/{tenant_id})
	GetQuotaStatus(w http.ResponseWriter, r *http.Request, tenantId string)
	// ListRates List rate records
	// (GET /api/v1/rates)
	ListRates(w http.ResponseWriter, r *http.Request, params ListRatesParams)
	// TriggerReconcile Trigger a full OSAC reconciliation
	// (POST /api/v1/reconcile)
	TriggerReconcile(w http.ResponseWriter, r *http.Request)
	// GetCostBreakdown Line-item cost breakdown
	// (GET /api/v1/reports/breakdown)
	GetCostBreakdown(w http.ResponseWriter, r *http.Request, params GetCostBreakdownParams)
	// GetCostReport Aggregated cost report (Koku-compatible)
	// (GET /api/v1/reports/costs)
	GetCostReport(w http.ResponseWriter, r *http.Request, params GetCostReportParams)
	// GetPipelineSummary Pipeline summary counts
	// (GET /api/v1/reports/summary)
	GetPipelineSummary(w http.ResponseWriter, r *http.Request)
	// CreateWallet Create a prepaid wallet
	// (POST /api/v1/wallets)
	CreateWallet(w http.ResponseWriter, r *http.Request)
	// GetWalletStatus Get wallet status
	// (GET /api/v1/wallets/{id})
	GetWalletStatus(w http.ResponseWriter, r *http.Request, id string)
	// AdjustWallet Adjust wallet balance
	// (POST /api/v1/wallets/{id}/adjustments)
	AdjustWallet(w http.ResponseWriter, r *http.Request, id string)
	// GetWalletLedger Get wallet ledger entries
	// (GET /api/v1/wallets/{id}/ledger)
	GetWalletLedger(w http.ResponseWriter, r *http.Request, id string, params GetWalletLedgerParams)
	// TopUpWallet Add funds to a wallet
	// (POST /api/v1/wallets/{id}/top-ups)
	TopUpWallet(w http.ResponseWriter, r *http.Request, id string)
	// GetLiveness Liveness probe
	// (GET /healthz)
	GetLiveness(w http.ResponseWriter, r *http.Request)
	// GetReadiness Readiness probe (checks database connectivity)
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetEntitlementValue operation middleware
func (siw *ServerInterfaceWrapper) GetEntitlementValue(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "customerID" -------------
	var customerID string

	err = runtime.BindStyledParameterWithOptions("simple", "customerID", r.PathValue("customerID"), &customerID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "customerID", Err: err})
		return
	}

	// ------------- Path parameter "featureKey" -------------
	var featureKey string

	err = runtime.BindStyledParameterWithOptions("simple", "featureKey", r.PathValue("featureKey"), &featureKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "featureKey", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEntitlementValueParams

	// ------------- Optional query parameter "model" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "model", r.URL.Query(), &params.Model, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "model"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "model", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEntitlementValue(w, r, customerID, featureKey, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDebugConfig operation middleware
func (siw *ServerInterfaceWrapper) GetDebugConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDebugConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IngestEvent operation middleware
func (siw *ServerInterfaceWrapper) IngestEvent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IngestEvent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListQuotas operation middleware
func (siw *ServerInterfaceWrapper) ListQuotas(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListQuotasParams

	// ------------- Optional query parameter "tenant_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tenant_id", r.URL.Query(), &params.TenantId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tenant_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenant_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListQuotas(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateQuota operation middleware
func (siw *ServerInterfaceWrapper) CreateQuota(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateQuota(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteQuota operation middleware
func (siw *ServerInterfaceWrapper) DeleteQuota(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteQuota(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateQuota operation middleware
func (siw *ServerInterfaceWrapper) UpdateQuota(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateQuota(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQuotaStatus operation middleware
func (siw *ServerInterfaceWrapper) GetQuotaStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tenant_id" -------------
	var tenantId string

	err = runtime.BindStyledParameterWithOptions("simple", "tenant_id", r.PathValue("tenant_id"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenant_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQuotaStatus(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRates operation middleware
func (siw *ServerInterfaceWrapper) ListRates(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRatesParams

	// ------------- Optional query parameter "tenant_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tenant_id", r.URL.Query(), &params.TenantId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tenant_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenant_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "format", r.URL.Query(), &params.Format, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "format"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "format", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRates(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerReconcile operation middleware
func (siw *ServerInterfaceWrapper) TriggerReconcile(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerReconcile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCostBreakdown operation middleware
func (siw *ServerInterfaceWrapper) GetCostBreakdown(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCostBreakdownParams

	// ------------- Optional query parameter "tenant_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tenant_id", r.URL.Query(), &params.TenantId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tenant_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenant_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "resource_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "resource_type", r.URL.Query(), &params.ResourceType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "resource_type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resource_type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "format", r.URL.Query(), &params.Format, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "format"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "format", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCostBreakdown(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCostReport operation middleware
func (siw *ServerInterfaceWrapper) GetCostReport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCostReportParams

	// ------------- Optional query parameter "tenant_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tenant_id", r.URL.Query(), &params.TenantId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tenant_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenant_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "resource_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "resource_type", r.URL.Query(), &params.ResourceType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "resource_type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resource_type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "group_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "group_by", r.URL.Query(), &params.GroupBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "group_by"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group_by", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "resolution" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "resolution", r.URL.Query(), &params.Resolution, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "resolution"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resolution", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "period" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "period", r.URL.Query(), &params.Period, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "period"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "period", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "format", r.URL.Query(), &params.Format, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "format"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "format", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCostReport(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPipelineSummary operation middleware
func (siw *ServerInterfaceWrapper) GetPipelineSummary(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPipelineSummary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWallet operation middleware
func (siw *ServerInterfaceWrapper) CreateWallet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWallet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWalletStatus operation middleware
func (siw *ServerInterfaceWrapper) GetWalletStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWalletStatus(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdjustWallet operation middleware
func (siw *ServerInterfaceWrapper) AdjustWallet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdjustWallet(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWalletLedger operation middleware
func (siw *ServerInterfaceWrapper) GetWalletLedger(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWalletLedgerParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWalletLedger(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TopUpWallet operation middleware
func (siw *ServerInterfaceWrapper) TopUpWallet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TopUpWallet(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetLiveness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.GetReadiness)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/events", wrapper.IngestEvent)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/rates", wrapper.ListRates)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/quotas", wrapper.ListQuotas)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/quotas", wrapper.CreateQuota)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/quotas/{id}", wrapper.DeleteQuota)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/v1/quotas/{id}", wrapper.UpdateQuota)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/quotas/{tenant_id}", wrapper.GetQuotaStatus)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/wallets", wrapper.CreateWallet)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/wallets/{id}", wrapper.GetWalletStatus)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/wallets/{id}/top-ups", wrapper.TopUpWallet)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/wallets/{id}/adjustments", wrapper.AdjustWallet)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/wallets/{id}/ledger", wrapper.GetWalletLedger)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/reports/costs", wrapper.GetCostReport)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/reports/breakdown", wrapper.GetCostBreakdown)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/reports/summary", wrapper.GetPipelineSummary)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/customers/{customerID}/entitlements/{featureKey}/value", wrapper.GetEntitlementValue)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/reconcile", wrapper.TriggerReconcile)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/debug/config", wrapper.GetDebugConfig)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7D3rchu3eq+C2faHPLMiJTvntFHm/HCknFSNfaKIdjyZWLMDLj6SCLHABsBSZjya6UP0CfskHVz2jiWX",
	"tiQr7fkVmYvLh+9+A/IxSkWWCw5cq+jsY6TSFWTY/vmSgdTXkApJzD9zKXKQmoL9mAquigzsl4WQGdbR",
	"WUREMWcQxZHe5hCdRbzI5iCjuzhaUAkkMYOaw7GGY02zxgylJeVLM4O2l6Zc//WrehzlGpZuaUYzqpMN",
	"ZgWMBCYDDTLhOLMTejvnIKkgwU9KYx2epIFjrhManqdXEtRKMJLkqR4F5V31i5j/Bqk2q5wzUZDvNsDt",
	"EgRUKmmuqeDRWeObQqeTE6S0LFJdSCDHmSCA/nP24z8Q8A0wkZvt2tQkWOP+mnY5lOMtE5h8g9QK54AI",
	"5MCJQoIjA+AEzQDQucjyQsMlVxrzFOzEC6xxjM5ZoTTIxi+vMZ5V/5xEcSQ4/LiIzn79GP2rhEV0Fv3L",
	"tObJqWfI6dAW0V28Z2IHgr0TWgBGdzd3scVPKrgGrh1VPkbwAWc5MwTCec5oig3Spr8pwYe5uZ4DG32M",
	"5+np8xeh0UoUMu3sMhUKp1PLupQvj1PBGKRayOD8HNINSGXJ2FzkdHISHF84HguyLs1gvNSW2AkxkmOX",
	"H7i4dayjzpA50yR1lE2oJ+2E0QWk25RB7Ac4CvZ+N4zNmr9SvgAJZgkt1sDVpFBAoriBgKERnYPcxZGE",
	"3wujtKKzX1v49GMrIlna3gSltcN3PbT8OHt5jkqKooqi6BzjGXLc2JNUj4shRUMKaRkxUZAKTtRIjbgS",
	"Sicl7XqLckEgSUXBdVclv3geVMm71GSWs0/TobdCro3aNsCETjdkIYKadEiZjKbRz693EQlrzMQyoRqy",
	"4FlSIUGNRGaaF4kZf9ChP5kTSiEcokIGmZDbZEnnI8GvJxx4gAdgojArKP2tBLwm4pa/BscDXV/Hs34f",
	"yAVlGqQdhQmhBuGYXbVmD+jICoS9QF2DygVX0AesNNuGz+wPuw1oc01x2wAFS4m33jPCB61jETbiCOI2",
	"hFalE5z19Mowc6Y71VRaSKPat2HFOMQve5xB+xnIQf5lLoXBwpAISXCmY+/3wZPuVpSFGrIPQ3S6hlxI",
	"HWb+e+DwOFpKUeTJfHuov21QwQrt/Zj+PkJjto9ffxDrwhzyjR28Bwf3KGt+wc8TtAZl9kE+JGJjZWuM",
	"9LRt45UEZRw7wdkW3a6Ao5pefyOYsm3IRQSuZZtxGvrUMkoQBMoXEldRTXLAyVSR5wwy4BrL7fiJQXRL",
	"wBreYcZAX8PvBbi1OkhvYJLAAhfMbPN2dhHCxh5dMTKsVC3OHIGTNj923N1605Bfe0HxkgulaXrJF6J/",
	"fFzoVUKVKkAmhWQDqlppkSUZaElTlaSCL+gyybFehdkP5sUyIVit5gLLJi7mQjDA3DHIEpROGFUaeIIJ",
	"kQN8ZJw945KQebLyzNDma+MJzrEC9Pb6FbqleoVSCQS4ppgplGG1DsUMcWRcvhL3H8OfGWyADRsaypeJ",
	"kQa5wYOjLMaMxAcHmMAoMcAP4t6OSHGSgtSJAh3Gph1lY6ThMcbB3AewND5fShnsHqZyVvB1soJ0EG4/",
	"hHICH3YN2Al0SKi/45pqpyB+Lq18myEur66OjYLGms4ZIKgnIOsXTNBrrNMVKKRXrc92PZ+LQQspMjvg",
	"8uoKwQcNkmN2XMUWOSuWlKOUUeB60osp5pgZv3xsQIfVyzQFpQaouwGJl2MXK9TYsUH0SinksF0F8zns",
	"qzR1khsW0kelff+WiXTdXz/Dcu1Myhgn4RXeujNLfHvwnIPckWpWhd0DZt3twIMb0sNDwakOe2vjXdtd",
	"274pDx/2QMYczlGw9POHAW67Agev3vIHDpwdwkA7X9hTHjZRMB0QerCZMeNbTpAR2FwrNBd6hRgscbpF",
	"mUjXyNEFYU6s+pCA2W4d4iZMAnmJdAVJapwYKrjTlKoP8ayYK9BILFAuRZbrcmA8Jmy3e5CE8rzQh+7w",
	"DcqxVEDMAZCYK2Mv5pRRvY0RFxrNKWNAkIIcS6zB+pdjQBJZzqBz5FHzlE5SMHZrd7Ite+CkzLBXbFOg",
	"w18Gszj242DQK+QSc/qHA3VgiTZrjDt+LsWGkgFsSsBKcONQ7OeaHkXRkTidihfTC4B8BrBG16fPxjGH",
	"dG58OL+5e87nZ7JUMW8c8H7zpQ4xCeUjofTjRaFHT9CYHcYAhQI5Mi9xRXNglMOsyDKvpwPpo53BJKMb",
	"SHzCfNcQKw27Bmyyga+V074TDqOrBj/dJtYGBL+H8PJTITQeqsrCYgGpNiAbZ3N82aaep8XgLF4who2G",
	"OtOygCdVsh1Ry22rkm8pY9Zg2u9nKBNcr9g2RrcAa/Nfm76IkZDIxaoTdOFCeYW0QO8jP+F9hOgCiYxq",
	"DWQSDPAFo2UuoFUT4wshUxdEuDHdLQjw7fto8glZg8/NILbzCm24bVcAqkYYDBoTiZdgHIRPz0HE1kPt",
	"7/eWU6vyjefzu+H9CTr3CRaUCgIKHb2dXcTou7fXMQKdTp4hyglNsQaE0bwgS9Bu4jdI6BXIW6rMl8pn",
	"MttOgiXAsOzNNNaFCuQ9DGLU6BRhs7sigIwD+yusRN1b+4Mn6Fg6trhlT5K4EYS26fwmwFFoDVuFMpzn",
	"QIxMzCVY7xIdGQ00XWCm4FkUIFTJSofRdDhI3ZGi9qK48+yjGKLJXAGG6KReQR77nR1zI2VnGnHIe2lZ",
	"P/JYpcJg0k5QCD5QpYPocwPuC/JDK3J2uXdUr2pJw4yNaBFpmsa7+DM7lh5NDPaWA2+6xG+cEwGX1IqE",
	"zVMabwW5g9rBNrI0m1xjDcOtXI2qWifx1Yq0jTWctYLn+NAqHOx2d/8k/ktVJB+0r2uxLnx6+1Oqjrmk",
	"KSQ5yKTUZPWJIKUZZiEsHGj29+JDU5DWOR5oDAKZ7FCM5vt4HfKGDhQmeurhGjChHJQakVPcV6/iQiMJ",
	"mAQ5WVXqB3iRRWe/RuVQLnTi/r4Z5TfsMy+NnapOJbEe55NYxPUN1icxUJF7+em4YHkOEs1FwYn1xCjI",
	"b5DhHpQB5goV3LoftijSV5QDbNbIKTbzvB3AQwlfV357mRroBotwob6C4YPvVFplmi2x7DuYuRhp3Rz0",
	"r4AsQX7HdSiyPQx2XxhI8MLnqUYduAyet8mA1hsgWzM9Zouhh3X17ka0hWdQee2lw2j9PUiwOLq15Bnv",
	"rJS14LBpDRZt9pNywYQYT8r7JkMHjUVBw9XOsu8yGc5v7Y1TfTdmciCiHqcsbhQiORC3wzwyFDc+Bo+U",
	"k/omzZoZAjkDo79vDuWVT6aghAxTm+0d2xF/GNU/2f/erQLiyPjZlDePu7/GfOeKVmKgvdQoY5Rhjpcu",
	"HfQ///XfvjDkehqo4HGVr4iRK7vHLoyb+gxHPT1G7gCtnzAnKF1huYQ5TtdI2pYhcyLjp2nrcJwbKFyn",
	"9rkLlSR6eXUZxVHVSh6dTk4mJ7ZCkAPHOY3OoheTk8mLKI5yrFcWw1Oc0+nmdOryZiDV9GP55+XF3bRR",
	"HVfTjwvAJrL4AbZ30yofuIRAHugadCG5Qpj3C+zSe1aoUaS38dDYajs6X0G6VggzVkbHCyHt9BJ2i0JZ",
	"ArFcSlhiDcjzQYxsGdch2lfX7d2GHFzF55JEZ9H3oHvNBgZzElu4lI1wO/c6yu2nyLE/uryIDDdFZxbl",
	"UZn8jGokR02Xyllv36gcsmndHf/uSILWsEVHxmOWG1+RWxT2g6dZO5vwLAxUTd/PA+q1IMCQWRQdGUky",
	"usJKtysMbkGjoiwcuo5FypcVTL8XYINVD5Qrmu3a/8YGU5anLE8/PznxKQTtb9/0Ln1Ud6f2RTo9DrDq",
	"oZsc7nSYGJn76j6BaDVlBCB4jZnBMhBkCXpni1W+EtPth/EygKatzpjUiJTRL3hpGNtMim7MOqWCsF1d",
	"U9f7tV/skcKcavoHELShcFumhGXBuevMN8v48uoEzSCVoBXCEnzDFhISqZW45Qgr5HU1WjC8VEE5vTDA",
	"nTvYHpAZOs10AULUI9pn7JDE4cmgw/gl7aHoqMLdswZBfizPrNp0qetRebA9ruxTwOigS2cTmzsSUgPx",
	"1u0RLwF5C2hV5LHLyzSB6LPApbW87rJdVfD9VpDtvZG+cZvvrh0FG+1412O6r4buVWFLDyD2iLkUKSgF",
	"5NE1xiXfYEaJJXqMMqqUkcvyVGhBgRFlK2pzTBqNLw7Qrw8CdH/6hBRu/igXPSB15XQP6BFmNuHjPTIj",
	"SHdx9JfHxO9MC+NVGAR6Ihv8LjBlhYSugrZQBiS0cQO0VAPua1sF1AUAr5TbwvGKKv2TG7LHffm7tcVo",
	"vu17Lx2jXDv3BzkG71bA0fvIiMz7KC7T4QoBTle+MuI6eH32f1rn9aeNiCEMk2esJkBl3GQ2jOLIlqBC",
	"WcDP9SDaHB4oyIy7Ndstiewd26i72Juv+/KxfT41zGGss4f5scXkJ0PCAbGwoNU+fkMIPDff2IK9CrC8",
	"6/y3wx7IHrRINcYgnD7c1oF6E/J5pke3Kz8bq+L8GJvXR0elbSlNirEnrhAR29grFVlG9ZfT0GHmcxyE",
	"sNdKxg7a0D3EhT1VPP1IyZ1zABi4ZFubPy/s7yV/7tTJjpzS1Q+Hokmrh4cDtv23bm/GODAOFHemL+ex",
	"OIJcXjgAvnpMXWU2NgHsQhScdBhmJhb62OGm5JoBjVUEFNZbm7p8agzxBNTmyeOqTZ9CNrwVFAFHJ4Lm",
	"hS5J4KqSWlLY2ArMl5YLp2GdX+/dd1/3fVoC41BpM4QfqNLGRAxKTUDDVh7o3d5sROVNVmlsm3mCjfE9",
	"HNrmwARfmi9a2EyFW97EpykriG8+rJp45uVVaYXoYlfDTjBb0ezA2SPsb3ZnEZtu+Ph83c1DS1mngj7I",
	"GqrqQnrcbJn3SIS0DoiyaaoalU/JB/4e2h1jlnGxB3aPpFSNzLtTdYwhM9KrMxPz5y5Zy7Y+OWv0XRkS",
	"Vnkhhc5nPyP4YP5GG4r9NZa/pWpjEOvSTmdIwwc9TdWmLwjGvb+2II6LSu1xHjA2nYF2nbyp2ryPLKLr",
	"Ew5s5e1oKORM1ebhI80db11U1B/V0NPoOBsTRsZRSdc2dJ1qyOznMpxnRWZ0JYkr4sSt/qe41aQV1w1X",
	"cdXvFrebTeKy0hlXjU9xo8nJ/q3iBkBxu10tbnWh9Qk1GCk3heXpxcst6Gr94AStrR7Ku77DueOZxtKm",
	"juc4XS+lbSkqp1EX5MmCT1CpS756/rVtsOeAqNEsZRLOWMilBBXI3L6RdLkEeV0B05OP5/eca+wcQDsA",
	"Bt6V2ps/uR5azRi1518/Hmd0AAkg3zHri8cHCaR1AssqB3Q9Qc8DCKNFwRiyVfY2lUbUQVyRXE0r12yv",
	"5aOc0A0lBWaupu9vBTmVZTXQsX0AABHQmLL7s3zfg269t/PF07L1BqVSRv7ZtNAm7cbVw2ysUSjI+v1H",
	"v/zyyy/Hr18fX1wYrF3//fzFixdfP/sGkca1mgWVTuk6Za/dzZ8hYyxFdhg433FyADBc3A6hXRy272v8",
	"gWZFhqS4tSu7RoWBxd1lkbhlZf0zJacnJ6EX1P6cns3417BqlTPeD/EuyJmld8MLqXveYv8SU8cxabz/",
	"1HRLWi9NxY3HsRoOS9WLNcK7sP08le6ynPHFMglWJDwDPC0Hh8OxcWedvp439Gfl5zgrEDYNZpYakS1Q",
	"WiF7ibsZ+MSozRfOQsRl8G9zLYaDGmbC3kpsvLIU+5K2Q7DEfAnKlbprcTTOlG+PykBjNGfuTQHGjK74",
	"QawLC+C0/arCtPVKQl3ZH7Q9Dk//fwzP94acJuYnNAPunwYN7VG9fRZUuFEVeFeVxfKHLnAWqVHVVBv5",
	"69ShKwiD+toykNfYOchjgrdOMwzjx7+/FtLb7o2vMQC8NlbWuI7eLJZvWhx5RLTN8VDjls86tkCpvPDn",
	"J8//enzyb1F8P06D2ICUlIBC1a5/bhfh/4bN7jzT9wkGG22MQps31egEvaN6JWwGvvztzCns2Pvw1gjH",
	"gUfo4v7zcpWZduv2XsXzLsM9rD/aD3AG65/2v2P/X5Z9vMQ5AA5N6MhYxUaH47Ox/oCqH6vYnSKt+odt",
	"vk0hnEqhXOo09w9fII3nDBQ6kvjWdSGpugu8DC3jVqAZu5Rm7O6BlvZDPQsa7e4DGw8ouN2tAlQqh6AS",
	"hU+JTbrAeart4wrXh9/qpAw1lbjrIQ/VZRh4sfKRu0taV6QCmHffn0x/yVNtG8kl5JgSf7ujwXvvPJuF",
	"eK/qGwmqo1dCrBUqcmMN/aWRywuXIomRXgFHC8yYsslaW8YsffY6QVvdf6groXWHXezfLCtfdvDvN4Q7",
	"rlu3pPaEEe8qYIXcdy/iCZUyW0ccloQvXMT8Ao0w/uBDhf3vQZf8WbVkjub+KSa/FUpnu5var4Si2ljN",
	"xmh7e8CeGgiiWQaE2lfnJugfxniHRpeXUWjmfTYg6Ki8NfSXk9OAKX5pl6iMwDi+vz9Wv3+TE7qf/UVM",
	"TvOSdYDpXla08+WtL9w0b3TZHyAF8ve/rR06fTxYgkwdYOiuD21Hl/JZ3os8RECZpdNgt3llGxw9H1dG",
	"BjPt7loqEouqynPvaff7rew3nqgbVcAPyNAntYPbBUokPblWGM+2rA3lIdyrRX5c5Du8/Dcif5v/U78/",
	"un5/YwnzdHQ7F/w4r9wMr+M7qpSgRcGJ1SV4n6e/Asz06o9devMV3QAHpR4yuN/fmjcDuaGp7+Cgm34R",
	"xgGJcinmTcvxH/aA/rS2+WDnYauHgR7ytP3Xh3Yf2D0TdM99EocCUT1zhI5I+f82KLgNxrBNb3Xvkvrl",
	"HUXQUepux1dzU8G57XSievssSDCzHshNWMu9EilmiIC9ipa5G5b21f9opXV+Np0yM2AllD7795PnJ/YF",
	"NL9Fb6mSd9zt/BbcqlacHrC+NW/ej6seW6jn+btx/XnXNneHJUHMdRrXc1xjVH+Ka1A1cPaebKgn/1Re",
	"mgq8XdWI/oNzS+0QOGWd23SYqruNG3D7FFZ/un1BoXGze1rd+LaMUb26YF/qrhe8vLoKYa7TVcQJshfB",
	"63mNfpy7m7v/DQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
